### ISSUE TITLE
Concurrency issue: Photos mixed up in albums when multiple publishing actions happen cuncurrently

### ISSUE THREAD

**Issue by StephenKing** [flingo64/PhotoStation-Upload-Lr-Plugin#2]
When I hit the `Publish` button for a different album for a second time, while the first export is still running, the photos end up mixed in the different albums. It seems that there is an issue with concurrency either in the Lightroom plugin or in the PhotoStation API.

Here is a log file (which looks good) of an export of 5 color and 5 b/w images:

> 08:38:31: Environment: plugin: 3.0.7.20150714 Lr: 6.0 OS: 10.10.4 Lang: en
> 08:38:31: processRenderedPhotos starting
> 08:38:31: initializeEnv starting:
> 08:38:32: FileStation Login(https://diskstation.example.com:5001) OK.
> 08:38:33: Login to Standard PhotoStation(https://diskstation.example.com) OK
> 08:38:33: processRenderedPhotos(mode: Publish).
> 08:38:33: --------------------------------------------------------------------
> 08:38:33: Environment: plugin: 3.0.7.20150714 Lr: 6.0 OS: 10.10.4 Lang: en
> 08:38:34: processRenderedPhotos starting
> 08:38:34: initializeEnv starting:
> 08:38:34: FileStation Login(https://diskstation.example.com:5001) OK.
> 08:38:35: Login to Standard PhotoStation(https://diskstation.example.com) OK
> 08:38:35: processRenderedPhotos(mode: Publish).
> 08:38:35: --------------------------------------------------------------------
> 08:38:39: Create dir - parent:  newDir: test bw newPath: /test bw
> 08:38:40: Create dir - parent:  newDir: test color newPath: /test color
> 08:39:05: Upload of "color1.jpg" to "test color" done
> 08:39:15: Upload of "bw2.jpg" to "test bw" done
> 08:39:39: Upload of "color2.jpg" to "test color" done
> 08:39:45: Upload of "bw3.jpg" to "test bw" done
> 08:40:11: Upload of "color3.jpg" to "test color" done
> 08:40:13: Upload of "bw4.jpg" to "test bw" done
> 08:40:42: Upload of "bw5.jpg" to "test bw" done
> 08:40:43: Upload of "color4.jpg" to "test color" done
> 08:41:15: Upload of "bw1.jpg" to "test bw" done
> 08:41:15: --------------------------------------------------------------------
> 08:41:15: PhotoStation Upload: Uploaded 5 of 5 files in 161 seconds (32.3 secs/pic).
> 08:41:18: Upload of "color5.jpg" to "test color" done
> 08:41:18: --------------------------------------------------------------------
> 08:41:18: PhotoStation Upload: Uploaded 5 of 5 files in 163 seconds (32.7 secs/pic).

The result, however, is that the *test color* folder contains 3 b/w images and 2 color images. The *test bw* folder contains 4 b/w images and 1 color image.

![screen-shot-2015-07-21-at-08 44](https://cloud.githubusercontent.com/assets/277561/8794566/0ea4fdfe-2f85-11e5-8fb2-7b6c24229cf9.jpg)

**Comment by flingo64** [comment]
Oh my! 
I can confirm this bug. It happens if
- you do at least 2 Publishs (not Exports) in parallel and
- the 2 Published (Smart) Collections are using the same Publish Service (below the same  Publish Service settings)

I think I understood the problem and I'm working on a fix.

**Comment by flingo64** [comment]
I was hoping to know and fix the bug, but the problem is different from what I thought. 
In fact, those mixed-up exports will happen not only in the above named situation but in general when you have two parallel export/publish sessions to the same PhotoStation (Standard and Personal are different). 

I think it is because of the PhotoStation session cookie that is used: it is the same for all Export/Publish sessions to the same PhotoStation .
I tested two parallel Uploads with the Synology PhotoStation Uploader and it worked perfectly, the only difference I could see was that they use different session cookies for the two sessions. 

Unfortunately, it seems that I cannot change/remove the session cookie in Lr in order to work with two different cookies, according to: 
https://forums.adobe.com/thread/776601?tstart=0

I will do some further investigation but I'm not sure if I'll find a solution.

**Comment by flingo64** [comment]
The issue should be fixed in v 3.0.9 (see release notes). Please check out and let me know if it works for you.

**Comment by StephenKing** [comment]
Cool, thanks for the amazing quick reaction! Just found the time to give it a try. Works well :heart:
