### ISSUE TITLE
Handle files with same names

### ISSUE THREAD

**Issue by filipkis** [flingo64/PhotoStation-Upload-Lr-Plugin#25]
I have a case where I want to use the option to rename the files on upload, but I'm getting into a problem when resulting name would be the same for two files inside a collection. 

Now I know I can handle this by using the uuid, but that just makes for a very ugly name (and unfortunately Photo Station will always display the file name if there is no title). 

For my case specifically, it would be enough if I could use metadata placeholders to set the title for Photos that don't have one, but I've seen other people had problems with duplicate names, so maybe adding some simpler (e.g. 3 digit identifier) that could be used when names are duplicate or if the plugin would automatically add a number or something once the file with same name is found.

**Comment by flingo64** [comment]
The plugin cannot easily remember which remote names were already assigned to which photo, because photos might be published during different Publish sessions.  The plugin 'sees' only those photos of the current Publish session. This is why the plugin will run into this exception. So effectively, there is no way for the plugin to decide on the fly to add a suffix or not, since it really has no idea which photos were already published under which name,
I agree the UUID as a whole is quite unhandy for renaming, but you might want to use an extract of the UUID as suffix, which will be 'almost unique' depending on the amount of photos sharing the same name and the length of the extract.
Here is an example to extract the last 4 hex digits  of the UUID:
`{LrRM:uuid .*(....)}`
