### ISSUE TITLE
Cannot open dynamic album path

### ISSUE THREAD

**Issue by derkork** [flingo64/PhotoStation-Upload-Lr-Plugin#29]
When I put lightroom in the background and then focus it, I sometimes get this error message.

![image](https://user-images.githubusercontent.com/327257/32407133-c8853002-c184-11e7-9af6-6e494ddef1ce.png)

**Comment by flingo64** [comment]
This message is exactly what you get when you right-click a Published Collection having the shown Target Album path (which is a dynamic album path) and then select "Show Album in Photo Station".  It means: you cannot use the function 'Show Album in Photo Station' for this Published Collections, because it has no single root album to show in Photo Station

I cannot imagine why Lr is calling the "Show Album in Photo Station" function in the scenario you explained. 

What do you mean with put Lr in background, is it on MacOS? Did you define any keyboard shortcuts or such?

**Comment by derkork** [comment]
I am running on Windows. What I'm doing is i just switch to another window and then click into the Lightroom window to bring it back into focus. I have found out that clicking the gray region marked in this screenshot triggers the messagebox. I happen to click that region when I focus the window:

![image](https://user-images.githubusercontent.com/327257/32409313-bc441f18-c1a9-11e7-8f94-bdded907f4e5.png)

**Comment by flingo64** [comment]
Cool!  Works for me. too! :-)
So, clicking this area is really a shortcut to the "Show Album in PhotoStation".  I wasn't aware of that! That's a real nice Lr feature,  not a bug.

;-) Martin

**Comment by derkork** [comment]
I would agree ;) 

Well maybe just disable the functionality to open the album in PhotoStation if the album has placeholders in it's name instead of popping up that messagebox...

**Comment by flingo64** [comment]
It's not possible to disable the function for a specific Collection: a plugin either supports it or not. If it's supported you'll see the "Show Album in Photo Station" or similar in the context menu of the Collections of that plugin. Now, what would you do if you click on that menu item and nothing happens? Click again and again and after all you'll write a bug report to the developer ...

**Comment by derkork** [comment]
I see. Maybe instead of popping up a message box you could display a toast like the one that comes up when the synchronization has finished (the "Booooring..." thing). It's one less click and the message box also looks like some real technical problem occured.  A friendlier error message would also help -  I'm a developer I basically understood what the problem was here, but not everyone might. But we're getting into nitpick-town here ;).

**Comment by flingo64** [comment]
Good idea! Done in v 6.5.2

Greetings to all citizens of nitpick-town!

;-)
