### ISSUE TITLE
Populating "Location Tag"?

### ISSUE THREAD

**Issue by PaulWalkerUK** [flingo64/PhotoStation-Upload-Lr-Plugin#32]
Hi,

I'm new to PhotoStation so still a bit unsure how it works. I've used this plugin to export a photo from Lightroom that contains GPS data as well as location information (Country, State/Province, City). When I look at the photo in PhotoStation, I can see the GPS and location fields in the metadata, but the prominent field at the top says "Location Tag (Add)". There is a button next to it which reveals a map when you click it. Is there supposed to be a way to populate the "Location Tag" field itself?

Thanks,
Paul

**Comment by flingo64** [comment]
You can use the map to add GPS coords (red pin) via right-click on the map or to add a location tag (blue pin) via the search field.  The GPS coords will be written back to the photo. Photo StatLr can sync the blue or red pin coords (see Wiki), but not the location tag.

**Comment by PaulWalkerUK** [comment]
OK, so is there anything I can set in Lightroom that will populate "Location Tag" when I export to Photo Station?

**Comment by flingo64** [comment]
PS obviously does not correlate those metadata items to its Location Tag, so the only way to set tht Location Tag is to call the respective API after uploading the photo itself. Unfortunately, you cannot do it at one go, because you have to wait for the PS indexing process to index the photo before it can be managed by the PS APIs.
I'm doing the same for videos, so I know how to handle it, but it requires more than just a few lines of code, 
Anyway, the idea is OK and I might want to work on it during the long winter evenings.

**Comment by flingo64** [comment]
The location tag translation is implemented in [Version 6.7.0](https://github.com/flingo64/PhotoStation-Upload-Lr-Plugin/releases/tag/v6.7.0) Please check out and test it!
:-)

**Comment by flingo64** [comment]
Seems, Paul is no longer interested in that feature. Closing the issue!

**Comment by PaulWalkerUK** [comment]
This is looking great, just what I had in mind, thanks 👍

**Comment by flingo64** [comment]
Actually, I started to use it and it's really cool. I use a unique template: 'ISO-Code/State/City/Location' over all my Collections and I decide on a per photo base how deep  the Location tag will reach.  
The biggest problem is that although Lr is doing the reverse geocoding (only so far for Lr 6) , the location tags have only the state 'suggested' and not yet store in the photo. You still have to acknowledge them manually. Didn't find an elegant way how to do it for a bunch of photos.
