### ISSUE TITLE
Feature Request: Duplicate published (smart) collection

### ISSUE THREAD

**Issue by mpeter1975** [flingo64/PhotoStation-Upload-Lr-Plugin#50]
There is a possibility to duplicate (smart) collections in the standard LR collection tree. It would be very nice and convenient to do the same within published collections or even between them. 

The export/import collection settings was not a full solution, because the Target Album and Rename To definitions were not imported.

**Comment by flingo64** [comment]
Importing/exporting Smart (Published) Collections is a Lr feature. In fact, it will only import/export the 'Smart' part of the collection. i.e the definition of the membership criteria.

The way to duplicate the plugin-specific settings is to put your standard settings for collections into the Default collection, so that when you create  or import a new collections, those settings will be duplicated.

**Comment by mpeter1975** [comment]
Good point. Thanks.
