### ISSUE TITLE
Synology Photos 1.3 integration

### ISSUE THREAD

**Issue by wissnia** [flingo64/PhotoStation-Upload-Lr-Plugin#67]
I got a question. Is the plugin works with version 1.3 of Synology Photos?? Is it tested with that version? 

I am wondering if my problem with publishing regards my setup or if it is because I have v1.3 of Photos.

During publish I got `405` HTTP error after an API call to: 

```
DEBUG: Photos_API: LrHttp.post(url='/webapi/query.cgi', API=SYNO.API.Info params='version=1&api=SYNO.API.Info&method=query&query=SYNO.API.,SYNO.Foto.,SYNO.FotoTeam.')
16:30:57
```

**Comment by flingo64** [comment]
Works fine with Photos 1.3.2-0327
Your url seems is missing the servername. It should look like:
```
21:31:38, DEBUG: Photos_API: LrHttp.post(url='https://example.com/photo/webapi/query.cgi', API=SYNO.API.Info params='version=1&api=SYNO.API.Info&method=query&query=SYNO.API.,SYNO.Foto.,SYNO.FotoTeam.')
```
Please, check the server address and protocol in the Export/Publsh Service dialog.

**Comment by wissnia** [comment]
I intentionally removed it. It doesn't work either with IP address or servername of my NAS.

**Comment by flingo64** [comment]
It's the very first API call from the plugin, so probably your URL isn't correct. Check what happens if you enter the URL (without the params) in a Browser. You should get back a HTTP 200 with JSON error:
```{"error":{"code":101},"success":false}```

If not, try the URL with default port `:5000` (http) or `:5001` (https) without path `/photo`. The plugin will automatically add `/?launchApp=Syno.Foto.App...` in that case in the dialog. The alias path  `/photo` or an alias port (e.g. 5080/5443) can be configured in DSM Login Portal

**Comment by flingo64** [comment]
Make also sure that the DSM account used by the plugin is not configured for 2-Factor-Auth

**Comment by flingo64** [comment]
Photos 1.3 is 'officially' tested and supported starting w/ version 7.3.0.

No feedback on last responses, closing the issue.
