### ISSUE TITLE
PSPhotosAPI.lua 852: bad argument #1 to 'format' (number expected, got nil) - Getting this error when try to publish

### ISSUE THREAD

**Issue by drissslim** [flingo64/PhotoStation-Upload-Lr-Plugin#68]
Hi,
I'm using the last version of plugin and I'm getting this error in popup window when try to publish my photos

`An internal error has occured: [string "PSPhotosAPI.lua"]: 852: bad argument #1 to 'format' (number expected, got nil)
`
Any idea how to fix that?
Thank you.
<img width="258" alt="Screenshot 2022-12-13 at 08 56 28" src="https://user-images.githubusercontent.com/1101251/207265548-3e2bc6ec-8a81-4f17-be38-2f7b24b4728b.png">
<img width="1064" alt="Screenshot 2022-12-13 at 10 28 19" src="https://user-images.githubusercontent.com/1101251/207279738-b1c2acf3-64cd-4a94-832a-7dc3cbb43332.png">

**Comment by flingo64** [comment]
Hmm, that's an errror in the error-message print function. :-( Will be fixed in the next release.
Meanwhile, you may fix it in your installed plugin, so you can see avoid the exception. 
In file PSPhotosAPI.lua, change line 852 from: 
`return string.format("ErrorCode: %d", errorCode)`
to :
`return string.format("ErrorCode: %d", ifnil(errorCode, 100))`
This will then return an 'Unknown error'  message so you can chase the real problem

**Comment by drissslim** [comment]
Hi, I'm getting other errors related to nil value also at line 1034 in the same file. Please find in attachment the error trace.
Thank you.
![Screenshot 2022-12-13 at 23 25 49](https://user-images.githubusercontent.com/1101251/207458464-ab240fb8-d440-4485-bcc3-ee4c8c7df0ff.png)
<img width="861" alt="Screenshot 2022-12-13 at 23 25 39" src="https://user-images.githubusercontent.com/1101251/207458523-6d0dfffd-eb0d-471c-a34f-dddaf34da773.png">

**Comment by flingo64** [comment]
Wow, two bugs in one day: not bad!

In PSPhotosAPI.lua, change line 1076 from:
`elseif not Photos_deleteFolder (currentFolderPath) then`
to:
`elseif not Photos_deleteFolder (h, currentFolderPath) then`

Will be fixed in the next release.

Thanks for reporting!
