### ISSUE TITLE
Add photos to albums in Synology Photos

### ISSUE THREAD

**Issue by diogosalazar** [flingo64/PhotoStation-Upload-Lr-Plugin#69]
In the new Synology Photos it is possible to upload images with any folder structure and then later on add said photos to 'albums'.
The web api for Synology Photos supports creating, updating and adding items (photos) to albums: `api=SYNO.Foto.Browse.NormalAlbum&method=create&version=1&name=%22%22&item=%5B5279%5D`, and `api=SYNO.Foto.Browse.Album&method=set_name&version=1&id=8&name=%22Test%22`. A photo can be in many albums, while still being in a single folder location. This is similar to Lightroom's Collections.

Are there plans for adding support to setting/managing published photo 'albums'?

Thanks

**Comment by flingo64** [comment]
Yes, there are plans to support Albums.

An 'Album' in Photos is the pendant to a 'Shared Album' in  Photo Station and there is comprehensive [support for Shared Albums in Photo StatLr](https://github.com/flingo64/PhotoStation-Upload-Lr-Plugin/blob/master/Documentation/06-Publish-Managing%20Photo%20Station%20Shared%20Albums%20in%20Lightroom%20via%20Photo%20StatLr.md) already. Besides the documented features, you'll also find an undocumented dialog for Managing Shared Albums under
 `Library `-> `Plug-in Extras` -> `Photo StatLr / Manage PS Shared Albums`
So, most of the conceptual and UI work should be done already, but the code dealing with (Shared) Albums has to be reworked completely to support a generic intterface to both Photo Station and Photos API.

**Comment by diogosalazar** [comment]
Fantastic! Anything I can do to help?
I have been looking at the plugin source and although I am not used to Lua I was able to add a method to `PSPhotosAPI.lua` and use it with in `PSUploadTask.lua` inside the `uploadPhoto` method to create an 'Album'  in order to create the albums in Photos (although I did not implement adding the recently uploaded photo to said album).
I am going to read the documentation [link](https://github.com/flingo64/PhotoStation-Upload-Lr-Plugin/blob/master/Documentation/06-Publish-Managing%20Photo%20Station%20Shared%20Albums%20in%20Lightroom%20via%20Photo%20StatLr.md) you sent me above but please let me know if I could be of assistance on this matter.

Cheers

**Comment by flingo64** [comment]
Assistance is highly appreciated! It would make sense if you could do the PhotosAPI implementation of the required basic methods. 

I still have to cleanup and adjust the the northbound export interface of the PhotosAPI and the PhotoStationAPI providers to be consistent. The biggest API naming inconsistency is because Folders were named Albums in PhotoStation and Albums were named SharedAlbums and that's currently reflected in the provider API and also in some of the PhotosAPI implementation internals.

Nevertheless, the list of required basic methods is quite clear:
-  getAlbums
- getAlbumId
- listAlbumItems
- createAlbum
- editAlbum (probably not for the first shot)
- renameAlbum
- deleteAlbum
- addPhotosToAlbum
- removePhotosFromAlbum
- createAndAddPhotosToAlbum
If you could think of coding those basic methods, I would provide you with a full signature of those functions and some hints where you can find similar code in the Plugin. 
Due to the upcoming events this project, I'm not sure if I can start it this year already.

Martin

**Comment by flingo64** [comment]
Version 7.4.0 was just released. It adds Shared Album Management for Synology Photos.
