### ISSUE TITLE
Fail to upload video files

### ISSUE THREAD

**Issue by quantissimo** [flingo64/PhotoStation-Upload-Lr-Plugin#8]
Hello,

I'm using PhotoStationUpload on Windows 10 and LR 6.0.

So far, it works as expected with photos but I noticed that it fails to upload videos.

My video setting is:

Include video files:
Video format: original, unedited

Here is the error log:

21:15:08: Environment: plugin: 3.6.0.20151025 Lr: 6.0 OS: Windows 8.1 Home Premium Edition Lang: en
21:15:08: processRenderedPhotos starting
21:15:08: FileStation Login(http://192.168.1.33:5000) OK.
21:15:08: Login to Standard PhotoStation(http://192.168.1.33) OK
21:15:08: processRenderedPhotos(mode: Publish).
21:15:08: --------------------------------------------------------------------
21:15:08: exiftool Listener(""H:\Lightroom Plugins & Presets\exiftool-10.02\exiftool(-k).exe" -config "H:\Lightroom Plugins & Presets\PhotoStation-Upload-Lr-Plugin-master\PhotoStation_upload.lrplugin\PSExiftool.conf" -stay_open True -@ "C:\Users\Ivaylo\AppData\Local\Temp\ExiftoolCmds-471039308.73861.txt"  -common_args -overwrite_original -fast2 -n -m "-RegionInfoMp<MyRegionMp" "-XMP:Subject+<MyRatingSubject" > "C:\Users\Ivaylo\AppData\Local\Temp\ExiftoolCmds-471039308.73861.log""): starting ...
21:15:27: Environment: plugin: 3.6.0.20151025 Lr: 6.0 OS: Windows 8.1 Home Premium Edition Lang: en
21:17:53: Create dir - parent:  newDir: 2015 newPath: /2015
21:17:54: Create dir - parent: 2015 newDir: 2015-12-03 Teo's Christmas Concert newPath: 2015/2015-12-03 Teo's Christmas Concert
21:20:05: Upload of "2015-12-03_Christmas_Concert.mp4" to "2015/2015-12-03 Teo's Christmas Concert" failed!!!
21:20:05: --------------------------------------------------------------------

**Comment by flingo64** [comment]
Could you please set the log level to Debug and retest.
So far, I can think of 3 issues:
1) exiftool(-k).exe may not work as expected, try renaming it to exiftool.exe
2) The target directory includes a "'", might be a problem,
3) A timeout issue.

**Comment by quantissimo** [comment]
Hello, Martin,

Sorry for getting back to your reply so late but I was preoccupied with other things meanwhile. The issue still exists. This time I put 2 videos: one mov (250 MB)  and one mp4 (380 MB).

The publish script copied the mov file and reported it as successful but fails at the mp4 file. When I checked, it turned out that the 250 MB mov file is now 16 MB.

It seems that the plugin does some conversion although I set it up to include video files (original, undedited). See: https://dl.dropboxusercontent.com/u/3447094/settings.JPG

Here is the complete log file: https://dl.dropboxusercontent.com/u/3447094/PhotoStationUpload.log

Best regards,

Ivo

**Comment by flingo64** [comment]
Hi Ivo,
the MOV-file is converted to MP4 since MOV is not natively supported by PhotoStation. Anyway, the conversion and upload did work (at some point in time, I have to retest). You cannot play the original video in PS, but if you change the "Video Quality" below the preview to "High" it should work, if not, let me know.

The MP4 video upload failed because of an timeout. The maximum time for upload is calculated dividing the filesize through a minimum of 24MBit/s. In your case (slow WLAN ??) the calculated 129 seconds for 389 MByte upload was obviously to short.  You may fix this issue by modifying line 205 in PSUploadAPI.lua
local timeout = fileSize / 3000000
by e.g.
local timeout = fileSize / 1500000

Let me know if it works, so I can integrate it into the main stream.

Martin

**Comment by flingo64** [comment]
Ivo,
Version 3.7.0 has two related changes:
- when uploading .mov files, now the converted .mp4 file will be uploaded __in addition__ to the original .mov file rather than replacing it.
- the upload timeout is now calculated based on a min upstream throughput of 10 MBit/s.

Please check out and let me know if we can close the issue.

**Comment by flingo64** [comment]
Video upload fixes are incorporated in Version 4.0.0
