### ISSUE TITLE
Suffix "_1" was added in the published file name

### ISSUE THREAD

**Issue by drissslim** [flingo64/PhotoStation-Upload-Lr-Plugin#80]
Hi,

I'm getting an issue with some of uploaded videos which are published in Photo 1.3 with suffix _1 and don't know why. The error getting in the log is :

15:03:04, ERROR: batchUploadMetadata('Videos/2014/02/140923-MOV_0359.mp4') failed!!!

The full filname in Lightroom is : Videos/2014/02/140923-MOV_0359.mp4
The published name is : Videos/2014/02/140923-MOV_0359_1.mp4

Could you please help on that ?

Thank you for your help.

**Comment by flingo64** [comment]
Photos will add the _1 suffix to the filename if there is already a file with the same name on the server.  Photo StatLr therefore checks before each upload via the Photos-API  if there is a file with the target filename already on the server and if so, will delete it before uploading the new version of the file. Unfortunately, sometimes the index of Photos is out of sync and a file which already exists will not show up on the Frontend nor via the API, so that Photo StatLr won't delete id and will upload a second version of the file, which will then be (silently) rename.
To fix the issue you will have to re-index Photos' personal or shared folders via Photos: login as user or admin, open settings and start a Re-index for the personal or shared area. Wait until done (this may take a while) and you will see the duplicate file afterwards, so you can delete them.

**Comment by drissslim** [comment]
That's working now after reindexing. Thank you very much
